CC = g++ -g

all: selection_sort std_sort

selection_sort: selection_sort.cpp
	$(CC) selection_sort.cpp -o selection_sort

std_sort: std_sort.cpp
	$(CC) std_sort.cpp -o std_sort

clean:
	rm -f selection_sort std_sort
